// lib/export-utils.ts
import jsPDF from "jspdf";
import type { Employee, SalaryRecord } from "@/lib/types";

// 1) Generate a simple PDF salary slip for one record
export function generateSalarySlipPdf(opts: {
  employee: Employee;
  record: SalaryRecord;
}) {
  const { employee, record } = opts;

  const doc = new jsPDF();

  const lineHeight = 8;
  let y = 20;

  const addLine = (text: string, bold = false) => {
    if (bold) {
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFont("helvetica", "normal");
    }
    doc.text(text, 20, y);
    y += lineHeight;
  };

  const monthNames = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
  const period =
    (monthNames[record.month - 1] ?? `Month ${record.month}`) +
    " " +
    record.year;

  const base = record.baseSalary ?? 0;
  const expenses = record.totalExpenses ?? 0;
  const total = record.grandTotal ?? base + expenses;

  // Header
  doc.setFontSize(16);
  doc.text("Salary Slip", 20, 15);

  doc.setFontSize(11);
  addLine(`Period: ${period}`, true);
  addLine("");

  // Employee info
  addLine("Employee details", true);
  addLine(`Name: ${employee.name}`);
  if (employee.role) addLine(`Role: ${employee.role}`);
  addLine("");

  // Salary breakdown
  addLine("Salary breakdown", true);
  addLine(`Base salary: ₹ ${base.toLocaleString("en-IN")}`);
  addLine(`Expenses reimbursed: ₹ ${expenses.toLocaleString("en-IN")}`);
  addLine(`Total payout: ₹ ${total.toLocaleString("en-IN")}`);
  addLine("");

  // Footer
  addLine("Generated by Power Moon Salary Tracker", false);

  const fileName = `salary-slip-${employee.name
    .toLowerCase()
    .replace(/\s+/g, "-")}-${record.year}-${String(record.month).padStart(
    2,
    "0"
  )}.pdf`;

  doc.save(fileName);
}

// 2) Export multiple records as CSV (e.g. current year)
export function exportRecordsCsv(opts: {
  records: SalaryRecord[];
  employees: Employee[];
  fileName?: string;
}) {
  const { records, employees, fileName } = opts;

  const employeeMap = new Map<string, Employee>();
  employees.forEach((e) => employeeMap.set(e.id, e));

  const headers = [
    "Employee Name",
    "Employee Role",
    "Year",
    "Month",
    "Base Salary",
    "Total Expenses",
    "Grand Total",
  ];

  const rows: (string | number)[][] = [headers];

  records.forEach((r) => {
    const emp = employeeMap.get(r.employeeId);
    const base = r.baseSalary ?? 0;
    const expenses = r.totalExpenses ?? 0;
    const total = r.grandTotal ?? base + expenses;

    rows.push([
      emp?.name ?? "",
      emp?.role ?? "",
      r.year,
      r.month,
      base,
      expenses,
      total,
    ]);
  });

  const csvContent = rows
    .map((row) =>
      row
        .map((cell) => {
          const val = String(cell ?? "");
          // escape quotes
          if (val.includes(",") || val.includes('"') || val.includes("\n")) {
            return `"${val.replace(/"/g, '""')}"`;
          }
          return val;
        })
        .join(",")
    )
    .join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = fileName ?? "salary-records.csv";
  a.click();
  URL.revokeObjectURL(url);
}
